# Generated by Django 5.2.7 on 2025-12-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_year',
            field=models.IntegerField(),
        ),
    ]
